name: Analyse Bash Sendgit

on: [push, pull_request]

jobs:
  shellcheck:
    name: Vérification syntaxe github.sh
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Analyser github.sh
        run: shellcheck github.sh
